name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Compilar a aplicação com Maven
        run: mvn clean package -DskipTests

      - name: Encerrar instância anterior (se existir)
        run: |
          pkill -f 'java -jar' || true

      - name: Subir nova versão da aplicação
        working-directory: /home/softexpertapi/actions-runner/_work/springboot-app/springboot-app
        run: |
          nohup java -jar target/integration-0.0.1-SNAPSHOT.jar > /tmp/middleware.log 2>&1 &
