name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Compilar a aplicação com Maven
        run: mvn clean package -DskipTests

      - name: Encerrar instância anterior (se existir)
        run: |
          pkill -f 'java -jar' || true

      - name: Subir nova versão da aplicação
        run: ./start.sh
